language: php

php:
  - 5.6
  - 5.5
  - 5.4
  - 5.3
  - hhvm

before_script:
  - composer self-update
  - composer install
  - gem install mime-types --version "< 3"
  - gem install --conservative mailcatcher
  - mailcatcher
script:
  - phpunit --coverage-text

matrix:
  allow_failures:
    - php: hhvm
    - php: 5.3